### ISSUE TITLE
Error when compile

### ISSUE THREAD

**Issue by Oyssster** [lzyplayer/ros_relocalization#1]
@lzyplayer,你好。我在编译的时候发现depends文件夹中的dbw_mkz_msgs文件为空，所以在编译的时候会报错。不知道你是否能更新一下代码？
十分感谢～

**Comment by lzyplayer** [comment]
你好，感谢关注！你可以通过
`sudo apt install ros-kinetic-dbw-mkz-msgs`
命令安装该包，即使./depends/dbw_mkz_msgs为空依然不会影响编译，我已更新readme，谢谢你的建议，如果有更多问题请让我知道，有需要请随时重新打开该Issue。
